//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMan.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackMan.Framework.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand cannot be blank..
        /// </summary>
        internal static string AssetBlankBrand {
            get {
                return ResourceManager.GetString("AssetBlankBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand must be between 1 and 255 characters..
        /// </summary>
        internal static string AssetBrandLength {
            get {
                return ResourceManager.GetString("AssetBrandLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost must be between .01 and 1500000..
        /// </summary>
        internal static string AssetCostRange {
            get {
                return ResourceManager.GetString("AssetCostRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location cannot be blank..
        /// </summary>
        internal static string AssetLocationBlank {
            get {
                return ResourceManager.GetString("AssetLocationBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location must be between 1 and 255 characters long..
        /// </summary>
        internal static string AssetLocationLength {
            get {
                return ResourceManager.GetString("AssetLocationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset must be assigned to room..
        /// </summary>
        internal static string AssetRoomRange {
            get {
                return ResourceManager.GetString("AssetRoomRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room ID must be greater than 0..
        /// </summary>
        internal static string RoomIdRange {
            get {
                return ResourceManager.GetString("RoomIdRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number must be specified..
        /// </summary>
        internal static string RoomNumberBlank {
            get {
                return ResourceManager.GetString("RoomNumberBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number must be between 1 and 255 characters..
        /// </summary>
        internal static string RoomNumberLength {
            get {
                return ResourceManager.GetString("RoomNumberLength", resourceCulture);
            }
        }
    }
}
